Models/Restaurant/RestaurantCreate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantCreate
    {
        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        public string Location { get; set; }
    }
}

Models/Restaurant/RestaurantDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }

        [Display(Name = "Average Score")]
        public double Score { get; set; }
    }
}

Models/Restaurant/RestaurantEdit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantEdit
    {
        public int Id { get; set; }
        
        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        public string Location { get; set; }
        
    }
}

Models/Restaurant/RestaurantListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantListItem
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Display(Name = "Average Score")]
        public double Score { get; set; }
    }
}

Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantRaterMVC.Data;
using RestaurantRaterMVC.Models.Rating;

namespace RestaurantRaterMVC.Controllers
{
    public class RatingController : Controller
    {
        private RestaurantDbContext _context;

        public RatingController(RestaurantDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<RatingListItem> ratings = await _context.Ratings.Select(r => new RatingListItem()
            {
                Id = r.Id,
                RestaurantName = r.Restaurant.Name,
                Score = r.Score,
            }).ToListAsync();

            return View(ratings);
        }

        public async Task<IActionResult> Restaurant(int id)
        {
            IEnumerable<RatingListItem> ratings = await _context.Ratings.Where(r => r.RestaurantId == id).Select(r => new RatingListItem()
            {
                RestaurantName = r.Restaurant.Name,
                Score = r.Score,
            }).ToListAsync();

            Restaurant restaurant = await _context.Restaurants.FindAsync(id);
            ViewBag.RestaurantName = restaurant.Name;

            return View(ratings);
        }

        public async Task<IActionResult> Create()
        {
            IEnumerable<SelectListItem> restaurantOptions = await _context.Restaurants.Select(r => new SelectListItem()
            {
                Text = r.Name,
                Value = r.Id.ToString()
            }).ToListAsync();

            RatingCreate model = new RatingCreate();
            model.RestaurantOptions = restaurantOptions;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RatingCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Rating rating = new Rating()
            {
                RestaurantId = model.RestaurantId,
                Score = model.Score,
            };

            _context.Ratings.Add(rating);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            Rating rating = await _context.Ratings.FindAsync(id);

            if (rating == null)
            {
                return RedirectToAction(nameof(Index));
            }

            RatingDetail ratingDetail = new RatingDetail()
            {
                Id = rating.Id,
                Score = rating.Score
            };

            return View(ratingDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, RatingDetail model)
        {
            Rating rating = await _context.Ratings.FindAsync(model.Id);

            if (rating == null)
            {
                return RedirectToAction(nameof(Index));
            }

            _context.Ratings.Remove(rating);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RestaurantRaterMVC.Data;
using RestaurantRaterMVC.Models.Restaurant;

namespace RestaurantRaterMVC.Controllers
{
    public class RestaurantController : Controller
    {
        private RestaurantDbContext _context;
        public RestaurantController(RestaurantDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<RestaurantListItem> restaurants = await _context.Restaurants
            .Include(r => r.Ratings)
            .Select(r => new RestaurantListItem()
            {
                Id = r.Id,
                Name = r.Name,
                Score = r.Score,
            }).ToListAsync();

            return View(restaurants);
        }

        [ActionName("Details")]
        public async Task<IActionResult> Restaurant(int id)
        {
            Restaurant restaurant = await _context.Restaurants.Include(r => r.Ratings).FirstOrDefaultAsync(r => r.Id == id);

            if (restaurant == null)
            {
                return RedirectToAction(nameof(Index));
            }

            RestaurantDetail restaurantDetail = new RestaurantDetail()
            {
                Id = restaurant.Id,
                Name = restaurant.Name,
                Location = restaurant.Location,
                Score = restaurant.Score,
            };

            return View(restaurantDetail);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RestaurantCreate model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ErrorMessage = ModelState.FirstOrDefault().Value.Errors.FirstOrDefault().ErrorMessage;
                return View(model);
            }

            Restaurant restaurant = new Restaurant()
            {
                Name = model.Name,
                Location = model.Location,
            };

            _context.Restaurants.Add(restaurant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            Restaurant restaurant = await _context.Restaurants.FindAsync(id);

            if(restaurant == null)
            {
                return RedirectToAction(nameof(Index));
            }

            RestaurantEdit restaurantEdit = new RestaurantEdit()
            {
                Id = restaurant.Id,
                Name = restaurant.Name,
                Location = restaurant.Location,
            };

            return View(restaurantEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, RestaurantEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(ModelState);
            }

            Restaurant restaurant = await _context.Restaurants.FindAsync(id);

            if (restaurant == null)
            {
                return RedirectToAction(nameof(Index));
            }

            restaurant.Name = model.Name;
            restaurant.Location = model.Location;
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = restaurant.Id});
        }

        public async Task<IActionResult> Delete (int id)
        {
            Restaurant restaurant = await _context.Restaurants.FindAsync(id);

            if (restaurant == null)
            {
                return RedirectToAction(nameof(Index));
            }

            RestaurantDetail restaurantDetail = new RestaurantDetail()
            {
                Id = restaurant.Id,
                Name = restaurant.Name,
                Location = restaurant.Location,
            };

            return View(restaurantDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, RestaurantDetail model)
        {
            Restaurant restaurant = await _context.Restaurants.FindAsync(model.Id);

            if (restaurant == null)
            {
                return RedirectToAction(nameof(Index));
            }

            _context.Restaurants.Remove(restaurant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Restaurant/Create.cshtml
@model RestaurantRaterMVC.Models.Restaurant.RestaurantCreate

@{
    ViewData["Title"] = "Create A Restaurant";
}

<h1>Create A Restaurant</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index"> Back To List</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Restaurant/Delete.cshtml
@model RestaurantRaterMVC.Models.Restaurant.RestaurantDetail

@{
    string title = "Delete " + Model.Name;
    ViewData["Title"] = title;
}

<h1>@title</h1>
<h4>Are you sure you want to delete @Model.Name?</h4>
<hr/>

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Id)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Location)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Location)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Score)
    </dt>
    <dd class="col-sm-10">
        @if(Model.Score > 0)
        {
            @Html.DisplayFor(model => model.Score)
        }
        else 
        {
            <span>No Ratings yet</span>
        }
    </dd>
</dl>

<form asp-action="Delete">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back To List</a>
</form>

Views/Restaurant/Details.cshtml
@model RestaurantRaterMVC.Models.Restaurant.RestaurantDetail

@{
    ViewData["Title"] = Model.Name;
}

<h1>@Model.Name</h1>
<h4>Restaurant Details</h4>
<hr />

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Id)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Location)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Location)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Score)
    </dt>
    <dd class="col-sm-10">
        @if(Model.Score > 0)
        {
            @Html.DisplayFor(model => model.Score)
        }
        else 
        {
            <span>No Ratings yet</span>
        }
    </dd>
</dl>
<div>
    <a asp-action="Edit" asp-route-id=@Model.Id>Edit</a> |
    <a asp-action="Index"> Back to List</a>
</div>

Views/Restaurant/Edit.cshtml
@model RestaurantRaterMVC.Models.Restaurant.RestaurantEdit

@{
    string title = "Edit " + Model.Name;
    ViewData["Title"] = title;
}

<h1>@title</h1>
<hr />
<div class = "row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                @Html.DisplayNameFor(r => r.Id)
                @Html.DisplayFor(r => r.Id)
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control"></label>
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back To List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Restaurant/Index.cshtml
@model IEnumerable<RestaurantRaterMVC.Models.Restaurant.RestaurantListItem>

@{
    ViewData["Title"] = "Restaurant Index";
}

<h1>RestaurantIndex</h1>
<a asp-action="Create">Create Restaurant</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @if (item.Score > 0)
                    {
                        @Html.DisplayFor(modelItem => item.Score)
                    }
                    else
                    {
                        <span>No Ratings Yet</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Restaurant", new {id = item.Id}) |
                    @Html.ActionLink("Details", "Details", "Restaurant", new {id = item.Id}) |
                    @Html.ActionLink("Delete", "Delete", "Restaurant", new {id = item.Id}) |
                    @Html.ActionLink("Ratings","Restaurant", "Rating", new {id = item.Id})
                </td>
            </tr>
        }
    </tbody>
</table>